kind: pipeline
name: update-preview

clone:
  disable: true

steps:
  - name: clone
    image: docker:git
    commands:
      - git clone --depth 1 https://github.com/sfosc/sfosc.git source
      - git clone --depth 1 https://github.com/Beanow/sfosc-pages.git target

  - name: build
    image: klakegg/hugo:0.55.6
    environment:
      HUGO_ENV: production
    commands:
      - hugo -s ./source -d ./target --baseURL https://beanow.github.io/sfosc-pages/

  - name: commit-and-push
    image: docker:git
    environment:
      SSH_DEPLOY_KEY:
        from_secret: SSH_DEPLOY_KEY
    commands:
      # Store the secret deploy key.
      - mkdir -p ~/.ssh && echo "$SSH_DEPLOY_KEY" > ~/.ssh/id_rsa && chmod 0600 ~/.ssh/id_rsa
      - cd target
      - git config core.sshCommand 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
      - git config user.email "bot@sfosc.org"
      - git config user.name "Deployment Bot"
      - ls -la .
      - ls -la ../source
      - cat index.html | grep generator
      - git add --all
      - git commit -m "Rebuilding site `date`"
      - git push git@github.com:Beanow/sfosc-pages.git master

trigger:
  event:
  - push
