kind: pipeline
name: update-preview

clone:
  disable: true

steps:
  - name: git-config
    image: docker:git
    environment:
      SSH_DEPLOY_KEY:
        from_secret: ssh-deploy-key
    commands:
      # Store the secret deploy key.
      - mkdir -p ~/.ssh && echo "$SSH_DEPLOY_KEY" > ~/.ssh/id_rsa && chmod 0600 ~/.ssh/id_rsa
      # This allows pushing without knowing github's key fingerprint ahead of time.
      - git config --global core.sshCommand 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
      - git config --global user.email "bot@sfosc.org"
      - git config --global user.name "Deployment Bot"

  - name: clone
    image: docker:git
    commands:
      - git clone https://github.com/sfosc/sfosc.git source
      # - git clone git@github.com:sfosc/preview.git target
      - git clone git@github.com:Beanow/sfosc-pages.git target

  - name: build
    image: klakegg/hugo:0.55.6
    environment:
      HUGO_ENV: production
    commands:
      - hugo -s ./source -d ./target --baseURL https://beanow.github.io/sfosc-pages/

  - name: commit-and-push
    image: docker:git
    commands:
      - cd target
      - git add --all
      - git commit -m "Rebuilding site `date`"
      - git push git@github.com:Beanow/sfosc-pages.git master

trigger:
  event:
  - push
